server:
  port: 9001

jdbc:
  url: jdbc:mysql://127.0.0.1:3306/java?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
  username: root
  password: 123
  driverClassName: com.mysql.cj.jdbc.Driver