server:
  port: 9002

jdbc:
  url: jdbc:mysql://127.0.0.1:3306/tally?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
  username: root
  password: 123
  driver: com.mysql.cj.jdbc.Driver

