server:
  port: 9001

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/java?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
#    username: root
#    password: 123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

jdbc:
  url: jdbc:mysql://127.0.0.1:3306/java?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
  username: root
  password: 123
  driver: com.mysql.cj.jdbc.Driver

